### ISSUE TITLE
Archive older Feedback on Server

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-GithubFeedbackForm#39]
We don't yet have this issue, but eventually we'll want a way to hide older feedback, specifically bug reports that we've already dealt with or text feedback that has already been put into a report.

Features I can see for this:

* add a datetime column for bug reports  / feedback
* add a "hidden" column, that when enabled, doesn't show that piece of feedback
* ~a way to filter or slice feedback by datetime (similar to [InterviewStats](https://github.com/SuffolkLITLab/docassemble-InterviewStats))~
* a way to mark / change the hidden column for a piece of feedback
* a way to see all feedback, whether or not it's hidden

**Comment by BryceStevenWilley** [comment]
This is a bit larger and unscoped. Going to focus on just the following for an MVP:

* an "archived" column.
* a way to mark a bug report as archived
* a way to see all bug reports, whether or not it's archived.

**Comment by nonprofittechy** [comment]
There are some JavaScript frontend tools that just take JSON and display it. That won't perform well at every scale, but what do you think? If it works with, say, 500 entries, that's probably fine and we can paginate. Might reduce development time for this feature.

Overall this feels like a fine idea. I guess this would replace the need for GitHub for some organizations. But consider offloading some of the responsibility back to GitHub. Even if we don't start issues on GitHub for privacy reasons: maybe it makes sense to transfer them to GitHub when they relate to a bug. And if you've done that, is there a good reason to keep the feedback on the server, or can we delete it at that point?

**Comment by BryceStevenWilley** [comment]
>  Even if we don't start issues on GitHub for privacy reasons: maybe it makes sense to transfer them to GitHub when they relate to a bug.

That's why I'm adding this feature; there's already a button that pre-fills a github issue (lets you edit it before making the issue though), and making that link back to the session[^1] is the next step. If we want any of the stuff on the server to be usable, we need to have a way to say "I've already dealt with this".

> And if you've done that, is there a good reason to keep the feedback on the server, or can we delete it at that point?

We do still need the session info itself while that GH issue is open (as mentioned in the footnote itself). A delete might be necessary for data compliance, but not sure if I'd want it to be a manual step or not.

You was hesitant on the filtering stuff already, but you've convinced me that I don't think we'll need that stuff, either now or long term.

[^1]: Safely, that is. It'll likely link to that piece of feedback on the server, which we can then open the session, so we don't expose the session id.

**Comment by nonprofittechy** [comment]
> > Even if we don't start issues on GitHub for privacy reasons: maybe it makes sense to transfer them to GitHub when they relate to a bug.
> 
> That's why I'm adding this feature; there's already a button that pre-fills a github issue (lets you edit it before making the issue though), and making that link back to the session[1](#user-content-fn-1-4ee5d0dc16d2ab168d44ce77fa90cd7b) is the next step. If we want any of the stuff on the server to be usable, we need to have a way to say "I've already dealt with this".

OK, I hadn't thought through the fact that the issue will link to a session. That makes sense to keep open in both places then. But we should be careful to avoid reimplementing GitHub issues as a Docassemble interview.
