### ISSUE TITLE
User not logged in cannot proceed / feedback panel issue

### ISSUE THREAD

**Issue by miabonardi** [SuffolkLITLab/docassemble-GithubFeedbackForm#48]
this portion of the question causes an error where the user when not logged in cannot proceed on the form 

```
  - label: |
#      I am interested in being a part of a user feedback panel
#    label above field: False
#    field: would_be_on_panel
#    datatype: yesno
#    default: False
#    show if:
#      code: |
#        server_ask_panel and not get_config('debug')
#      variable: reason
#      is: something
#  - note: |
#      If we do a user feedback panel, we will contact you by email.
#    show if:
#      variable: would_be_on_panel
#      is: True
#  - label: |
#      **What is your email address?**
#    field: panel_email
#    datatype: email
#    default: ${ user_info().email if hasattr(user_info(), 'email') else '' }
#    show if:
#      variable: would_be_on_panel
#      is: True
```

**Comment by miabonardi** [comment]
See https://github.com/LSVermont/docassemble-VTFeedback/pull/6

**Comment by miabonardi** [comment]
See also https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/pull/430

**Comment by BryceStevenWilley** [comment]
I can't reproduce this issue. I'm in an incognito window, not logged in with this in the config:

```yml
debug: false
github issues:
  ask panel: True
```

Doesn't seem to be causing an issue on apps.suffolklitlab.org either.  I know it's been a while since you reported this, but do you have more information about what the error was?

**Comment by nonprofittechy** [comment]
I think it's an issue when there is no ask_panel config. Should be reproducible on a new server without that section configured, if I remember right. I believe I helped Kris with the same issue

**Comment by miabonardi** [comment]
This was a tricky one. Sorry for not writing a better issue here. 

It happened on 2 different repos using the AL feedback form and we narrowed to this code section. 

Will message on Slack!
